# --- Constants ---
TEMPO_ANNIMATION = 10
SPRITE_SCALING_COIN = .15
SPRITE_SCALING_CAPITOL = 2
COIN_COUNT = 50

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Redneck Rumble"


# player Constants
SPRITE_SCALING_PLAYER = 0.8
PLAYER_X = SCREEN_WIDTH /4
PLAYER_Y = SCREEN_HEIGHT/4
PLAYER_INIT_VEL = 2

# bullet Constants
SPRITE_SCALING_BULLET = 0.8
BULLET_INIT_VEL = 10

# capitol Constants
CAPITOL_SHIELD = 200
CAPITOL_HIT_POINT = 100

# Supporter Constants
SPRITE_SCALING_SUPPORTER = .25
SUPPORTER_INIT_VEL = 2
SUPPORTER_HEALTHBAR_WIDTH = 25
SUPPORTER_HEALTHBAR_HEIGHT = 3
SUPPORTER_HEALTHBAR_OFFSET_Y = 12
PROTRUMP_MAX_HEALTH = 5
REDNECK_MAX_HEALTH = 10
REDNECK_PROBABILITY = 0.1
BOSS_MAX_HEALTH = 25
PROTRUMP_DAMAGE = 5
REDNECK_DAMAGE = 10
BOSS_DAMAGE = 25
REDNECK_HP_DECREASE = 5/60

# Health Bar Drawing Text
HEALTH_NUMBER_OFFSET_X = -25
FONT_SIZE = 12
HEALTH_NUMBER_OFFSET_Y = 60
SHIELD_BAR_OFFSET_X = -5

# Health Bar Drawing life bar
HEALTHBAR_WIDTH = 100
HEALTHBAR_HEIGHT = 20
HEALTHBAR_OFFSET_Y = 50
