# --- Constants ---
SPRITE_SCALING_PLAYER = 0.25
SPRITE_SCALING_COIN = .15
COIN_COUNT = 50

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Redneck Rumble"
MOVEMENT_SPEED = 2
BULLET_SPEED = 10
SPRITE_SCALING_LASER = 0.8